# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vbguest.auto_update = false

  # OS
  config.vm.box = "centos6.5"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
  
  #ssh
  config.ssh.insert_key = false
  
  # Networking
  config.vm.hostname = "platform"
  config.vm.network :private_network, ip: "192.168.38.112"
  #config.vm.network :public_network
  
  # Source Folder
  config.vm.synced_folder "../../", "/web/platform", create: true, owner: "vagrant", group: "vagrant", mount_options: ["dmode=777,fmode=777"]
  
  # Provision
  config.omnibus.chef_version = :latest

  # Chef
  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = ["./cookbooks", "./site-cookbooks"]
    
    #global
    chef.add_recipe "selinux::disabled"
    
    #main repo
    chef.add_recipe "yum-epel"
    chef.add_recipe "yum-remi"
    
    #nginx
    chef.add_recipe "nginx-repo"
    chef.add_recipe "nginx"
    
    #mysql
    chef.add_recipe "mysql-repo"
    chef.add_recipe "mysql"
    
    #php
    chef.add_recipe "php"
    
    #other tools
    chef.add_recipe "tools"
  end
  
end
